services:
  # Servicio de PHP
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: weather-api-laravel
    container_name: weather-api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - weather-api-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: weather-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - weather-api-network

  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: weather-api-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_api
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - weather-api-network

  # Servicio de Redis para cache
  redis:
    image: redis:alpine
    container_name: weather-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - weather-api-network

networks:
  weather-api-network:
    driver: bridge
